haskell/attoparsec

Data/Attoparsec/Combinator.hs
The example usage of "sepBy" invokes the nonexistent function "symbol".
=> Fix documentation of sepBy and friends.

Data/Attoparsec/Internal/Types.hs
I noticed when perusing hackage that a missing type parameter `t` is referenced in the docs.
=> Fix Parser type documentation

Data/Attoparsec/ByteString.hs, Data/Attoparsec/ByteString/Char8.hs, Data/Attoparsec/ByteString/Lazy.hs, Data/Attoparsec/Combinator.hs, Data/Attoparsec/Text.hs, Data/Attoparsec/Text/Lazy.hs, Data/Attoparsec/Zepto.hs
Marked top-level modules as `Trustworthy` with a comment explaining why they are not currently Safe. `Trustworthy` implies that the module exposes a safe interface (so, even though under the hood attoparsec uses, e.g. `Data.ByteString.Unsafe`, the API doesn't allow the user to do unsafe things) and that importing the module would not allow the user to break package invarients. If one of the modules I marked doesn't satisfy this, we should remove the `Trustworthy` mark.
solves issue #45
=> Safe Haskell annotations

Data/Attoparsec/Internal/Types.hs, Data/Attoparsec/Text/FastSet.hs, Data/Attoparsec/Text/Lazy.hs
This tidies up the Show instances for Result and IResult to ensure the result of show on these types is properly parenthesized.
=> Change the Show instances for Result and IResult

attoparsec.cabal
I kinda [made a thing](https://github.com/liyang/bitstream/compare/master) for `bitstream`, but it needs access to abovementioned internal modules to implement a new primitive parser.
Sort-of related: #2. Would you reconsider exposing `attoparsec`'s innards?
=> attoparsec.cabal: expose Data.Attoparsec.Internal{,.Types}

Data/Attoparsec/Combinator.hs
∙ I think this is the least surprising behaviour…
=> Data.Attoparsec.Combinator.feed: append input even on Fail

Data/Attoparsec/ByteString.hs, Data/Attoparsec/ByteString/Internal.hs, Data/Attoparsec/ByteString/Lazy.hs, Data/Attoparsec/Text.hs, Data/Attoparsec/Text/Internal.hs, Data/Attoparsec/Text/Lazy.hs
the following code can be copied to tests and run in both this patch and before.  the comment at the end explains the difference: with this patch, the <?> contexts will be contained in the error message.
module Main (main) where
import Data.Attoparsec.ByteString.Char8
main :: IO ()
main = print $ parseOnly (many1 "*" <?> "stars") "#**!"
-- 0.12.1.0 *" <?> "i(before #71):
-- Left "Failed reading: takeWith"
--
-- 0.12.2.0 (#71):
-- Left "stars: Failed reading: takeWith"
=> Report error contexts.

.gitignore, Data/Attoparsec/ByteString/Char8.hs
`isDig` unnecessary since there are `isDigit_w8` function.
=> Replace isDig with isDigit_w8

.travis.yml, Data/Attoparsec/ByteString/Internal.hs, Data/Attoparsec/Text/Buffer.hs, Data/Attoparsec/Text/FastSet.hs, Data/Attoparsec/Text/Internal.hs, attoparsec.cabal, benchmarks/Benchmarks.hs, benchmarks/TextFastSet.hs, benchmarks/attoparsec-benchmarks.cabal, tests/QC.hs, tests/QC/Buffer.hs, tests/QC/ByteString.hs, tests/QC/Combinator.hs, tests/QC/Simple.hs, tests/QC/Text.hs, tests/QC/Text/FastSet.hs
Add inlined version of takeWhile and takeWhile1
Inlining these functions can improve code generation significantly when
the predicate is statically known as it avoids boxing every parsed
character. Unfortunately, marking `takeWhile` itself as `INLINEABLE`
isn't sufficient to convince GHC to inline it.
Moreover, we refactor things to avoid the allocations associated with
the chunk accumulation list unless necessary.
Previously things looked like,
benchmarking takeWhile/T isAlpha
time                 32.33 μs   (31.70 μs .. 33.25 μs)
0.994 R²   (0.988 R² .. 0.998 R²)
mean                 33.02 μs   (32.36 μs .. 33.92 μs)
std dev              2.687 μs   (2.086 μs .. 3.476 μs)
variance introduced by outliers: 78% (severely inflated)
benchmarking takeWhile/TL isAlpha
time                 71.00 …
=> Inline and refactor Text's takeWhile and takeWhile1

attoparsec.cabal
It turns out a couple more changes are needed to make the benchmarks work correctly when obtained from Hackage—just making sure that all the modules, dependencies, and files are specified correctly so that `cabal sdist` includes everything it needs to.
See also https://github.com/iu-parfunc/sc-haskell/issues/7
=> Make cabal sdist package up the benchmarks correctly

Data/Attoparsec/Text/Internal.hs
#105 keep state around with the `Finished` as scanner is applied recursively and otherwise shortcutting might fail.
=> #105 keep state around with the `Finished`

attoparsec.cabal
The incomplete `other-modules` reported in #131 was a red-herring,
the actual problem was the missing upper bound on QuickCheck 2.10
which introduced semantic changes incompatible with the testsuite.
Fixes #131
=> Fix test-suite build failures "with GHC 8.2.1"

benchmarks/HeadersByteString.hs, benchmarks/HeadersByteString/Atto.hs, benchmarks/http-request.txt, benchmarks/http-response.txt
There two two unrelated issues with them. The first was that the samples had extra newline breaks in them which would cause the request and the response to be parsed incorrectly. The second was that the warp request parser was used incorrectly. It needs to be fed a list of bytestring that has already been split on newlines. The results of the changes are that the request parsers for both warp and attoparsec are significantly slower. The warp one is about 15x slower than it previously was because it previously did almost no work. It is not totally clear why the attoparsec one is slower, but it is 3x slower than it previously was.
=> Correct the http benchmarks

Data/Attoparsec/Internal/Types.hs
Just a small style fix that `hiding (getChar)` is unnecessary in `Internal.Types`
=> Remove unnecessary hiding getChar

Data/Attoparsec/ByteString/FastSet.hs, Data/Attoparsec/Internal/Fhthagn.hs, Data/Attoparsec/Text/Buffer.hs
`attoparsec` fails to build with GHC HEAD (8.11) after [this commit](https://gitlab.haskell.org/ghc/ghc/commit/74ad75e87317196c600dfabc61aee1b87d95c214), which moves `unsafeCoerce#` from `GHC.{Base,Prim}` to `Unsafe.Coerce`:
```
[ 5 of 21] Compiling Data.Attoparsec.Text.Buffer ( Data/Attoparsec/Text/Buffer.hs, /home/rgscott/Documents/Hacking/Haskell/staging/dist-newstyle/build/x86_64-linux/ghc-8.11.0.20200222/attoparsec-0.13.2.3/build/Data/Attoparsec/Text/Buffer.o, /home/rgscott/Documents/Hacking/Haskell/staging/dist-newstyle/build/x86_64-linux/ghc-8.11.0.20200222/attoparsec-0.13.2.3/build/Data/Attoparsec/Text/Buffer.dyn_o )
Data/Attoparsec/Text/Buffer.hs:51:43: error:
Module ‘GHC.Base’ does not export ‘unsafeCoerce#’
|
51 | import GHC.Base (Int(..), indexIntArray#, unsafeCoerce#, …
```
=> Import unsafeCoerce# from GHC.Exts, not GHC.Base

Data/Attoparsec/ByteString/Lazy.hs, Data/Attoparsec/Text/Lazy.hs
Previously, `Data.Attoparsec.ByteString.Lazy` just reexported
`Data.Attoparsec.ByteString.parseOnly`, which only accepts strict input;
same for `Data.Attoparsec.Text.Lazy`.
Documentation and pragmas were copied from the strict versions.
Closes: #143
=> Add `parseOnly` versions for lazy input

Data/Attoparsec/Combinator.hs
I was reading through the code and realised this:
`Parser` is already an `Alternative`, so `choice` is effectively [asum](https://hackage.haskell.org/package/base-4.14.0.0/docs/src/Data.Foldable.html#asum)  
They have exactly the same implementation, so we can use it directly instead of re-implementing it.
=> Use Data.Foldable.asum for Combinator.choice

Data/Attoparsec/ByteString/FastSet.hs, attoparsec.cabal
Tested with 
```cabal
packages: .
tests: True
allow-newer:
scientific:base,
integer-logarithms:*,
splitmix:*
```
=> Support ghc-prim-0.8 and GHC 9.2

Data/Attoparsec/Text/Buffer.hs, Data/Attoparsec/Text/Internal.hs, tests/QC/Buffer.hs
Tested with 
```cabal
packages: .
tests: True
source-repository-package
type: git
location: https://github.com/haskell/text
tag: 2.0-rc1
-- https://github.com/haskell-unordered-containers/hashable/pull/234
source-repository-package
type: git
location: https://github.com/Bodigrim/hashable
tag: e755258f81d397a255bf674911109af80b4ac57b
allow-newer:
scientific:text
```
=> Support text-2.0

attoparsec.cabal
=> Drop support of GHC <= 7.2

attoparsec.cabal
I'm not sure which repository is the source of truth but `https://github.com/haskell/attoparsec` seems to look right. Also url for git should probably have a `.git` suffix.
=> Update github urls in cabal file

.github/workflows/haskell-ci.yml, attoparsec.cabal
- relax `ghc-prim < 0.11`
- bump CI to 9.6.0, 9.4.4 and 9.2.6
- add `default-extensions: TypeOperators` to silence warning in GHC >= 9.4
- some cabal cosmetics
Superseds:
- #213 
Revisable bits published as revision 3: https://hackage.haskell.org/package/attoparsec-0.14.4/revisions/
=> Support GHC 9.6, bump CI

.github/workflows/haskell-ci.yml, attoparsec.cabal, cabal.haskell-ci
Hackage revision: https://hackage.haskell.org/package/attoparsec-0.14.4/revisions/
=> Allow bytestring-0.12 and test it in Haskell CI

.github/workflows/haskell-ci.yml, attoparsec.cabal, cabal.haskell-ci
Closes #223.
Published as revision 5: https://hackage.haskell.org/package/attoparsec-0.14.4/revisions/
=> Allow ghc-prim-0.11 (GHC 9.8), adjust CI cover GHCs 7.10 - 9.8

internal/Data/Attoparsec/ByteString/Buffer.hs, internal/Data/Attoparsec/ByteString/FastSet.hs
Fix deprecation warnings mentioned in #220 
Closes #220 
- #220
=> Fix memcpy/memset deprecation warning
